### ISSUE TITLE
Make socket code event-driven

### ISSUE THREAD

**Issue by HenryHRich** [jsoftware/jsource#100]

**Comment by HenryHRich** [comment]
The goal is to allow asynchronous sockets, for which an event (new data or newly able to accept data) generates a call to a J socket handler.  This will allow a J program to be fully event-driven, waiting for UI, socket, timer, or user events.

**Comment by interregna** [comment]
Is "asynchronous" separate and distinct from "event-driven"?

How will 'event-driven' be different from the architecture of the existing JHS server?

There's some previous work on async server code here:
 https://code.jsoftware.com/mediawiki/images/c/c6/Jbillserver.ijs

**Comment by HenryHRich** [comment]
I want to get back the asynchronous socket support that was in J6.02 for Windows.  This is not about  JHS Server, but about having the desktop application get event calls rather than having to poll sockets.

**Comment by HenryHRich** [comment]
There is a need to use event-driven sockets.

**Comment by bilam** [comment]
jqt already reimplemented sdasync. Isn't this what you had asked for?

**Comment by HenryHRich** [comment]
Bill says it's fixed.
