### ISSUE TITLE
Errors in build process in Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by Xliff** [jsoftware/jsource#14]
I am getting an error when attempting to build for Linux x64 under Ubuntu Focal Fossa 20.04:

```
In file included from ../../../../jsrc/f.c:6:
../../../../jsrc/j.h:102:25: error: ‘__builtin___sprintf_chk’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
  102 | #define FMTI            "%lli"
      |                         ^~~~~~
~~~
```

**Comment by bilam** [comment]
what's the version of your compiler?

**Comment by Xliff** [comment]
```
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bilam** [comment]
I think this warning is false positive, the line might had been there for 2 decades already and never had any issue with other versions of compilers.
please add try adding -Wno-format-overflow to cflags.

**Comment by Xliff** [comment]
@bilam - Thank you for the suggestion! I will report back my findings.

**Comment by Xliff** [comment]
@bilam: Was able to successfully build adding that flag to all of the build scripts in make2/

Thanks!
