### ISSUE TITLE
the sentence fails silently

### ISSUE THREAD

**Issue by jip** [jsoftware/jsource#168]
```j
   JVERSION
Engine: j904/j64avx2/linux
Beta-i: commercial/2022-12-13T15:14:45
Library: 9.04.06
Platform: Linux 64
Installer: J904 install
InstallPath: /home/user/j904
Contact: www.jsoftware.com
   do=: 0:`(_1:`0:@.(0&(+./@:=))@])@.[
   0 1 do S:0 (0 ; 1 0)  NB. succeeds
0 0
0 0
   0 1 1 do S:0 (0 ; 1 0 ; 1 _1)  NB. fails
   aa=. 0 1 1 do S:0 (0 ; 1 0 ; 1 _1)
   type < 'aa'
+-----------+
|not defined|
+-----------+
```

Henry Rich wrote Mon Dec 19 15:37:24 UTC 2022:
> Fixed for next beta.  The line should have given a length error on do.

References:
1. Cross-reference: [[Jbeta] the sentence fails silently](http://www.jsoftware.com/pipermail/beta/2022-December/010668.html), Igor Zhuravlov, Mon Dec 19 07:09:01 UTC 2022.

**Comment by bilam** [comment]
fixed
