### ISSUE TITLE
Chromebook build

### ISSUE THREAD

**Issue by jackokring** [jsoftware/jsource#170]
https://github.com/jackokring/jqt-chromebook-arm works. The makefile in `make2` had to be edited to remove clean, as the memory on the Crostini container is not large enough to do in one pass. Much `ctrl+C` and `make`. Then I built `jqt` and needed quite a lot of `-dev` packages from `Qt5`. Quite a lot of `.git` deletion ... blah, blah ...

**Comment by bilam** [comment]
You can use shadow clone if the history is not needed.

**Comment by jackokring** [comment]
I guess I'm thinking of https://github.com/mahlenmorris/VCVRack and some array to sample processing at present as options. Atoms as constant CV, lists as sequences ... so although I would've built it anyway, the next thing is opening the library in a thread (if I do it, reality says possibilities first), and wondering how the ASCII to bin IO formatting works. Is it just a `char* evaluate(char*);` with a `dlopen`/`dlclose`?

**Comment by jackokring** [comment]
So https://drive.google.com/file/d/17kOTu3sWycFuEb6ODlNE2Ibx7mcqlULA/view (image), and rank 2 for polyphonic, and rank 3 for ... longer sequences. I'm not sure. Needs floats out and an execute replacement tick in. All the `C++` stuff to wrap it should be easy. It doesn't have to be realtime, just making arrays.

**Comment by bilam** [comment]
If you don't have any specific bugs to report, then you can post your suggestions or problems to J forums instead of here. Thanks.
