### ISSUE TITLE
jconsole unicode support

### ISSUE THREAD

**Issue by bugsbugsbux** [jsoftware/jsource#172]
hi, when i type in jconsole in the terminal i cannot enter äöü etc. they just do not appear.

i know you cannot use them as identifiers but thats not the issue, i want to be able to use them in strings.

it is possible to do so in jqt and jandroid, so i would consider this a bug.

note too, that it is not a problem with my terminal, as i can type them without any issue as long as i am not in the jconsole repl.

i really need this to work, because i want to write my code in neovim and send it to the repl from there - i cannot send it to jqt.

thanks for the awesone work,

kind regards

**Comment by bilam** [comment]
You didn't tell which platform and terminal you are using. 
I think it depends on platform and terminal.
I have no problem entering accent characters or chinese on macbook jconsole.

**Comment by herrvonvoid** [comment]
very weired as libedit should now support unicode by default. anyhow, the workaround seems to work, thanks!

**Comment by bilam** [comment]
what is the version of your libedit.so ? Is it 2.x or 3.x ?

**Comment by herrvonvoid** [comment]
my the version my packagemanager tells me is 20221030_3.1-1, so i guess 3.1
