### ISSUE TITLE
linux installer requires dpkg (update-alternatives)

### ISSUE THREAD

**Issue by herrvonvoid** [jsoftware/jsource#175]
The linux installer requires update-alternatives from dpkg, which is debian specific. other distros do not use dpkg. it would be awesome if it would not depend on this!

**Comment by bilam** [comment]
Which line and which file did you refer to?

**Comment by moon-chilled** [comment]
looks like pacman.ijs:1687 uses update-alternatives

**Comment by bilam** [comment]
Fix (by adding || true) for both places will be available in the next release

**Comment by herrvonvoid** [comment]
awesome thanks
