### ISSUE TITLE
linux install-usr.sh fails

### ISSUE THREAD

**Issue by herrvonvoid** [jsoftware/jsource#176]
system: up to date arch linux (6.2.10-arch1-1)
issue #175 is not the problem here, I appended '|| true' to the releveant line in the script

trying to run `bin/install-usr.sh` from the linux download fails with the following message `cp: cannot stat 'libgmp.so.10': No such file or directory`.

the failing line is `cp libgmp.$GEXT "$LIB/libjgmp.$GEXT"`.
there is a file `libgmp.so` in the `bin/` folder, which might have been meant. GEXT is explicitly defined as `GEXT=so.10` so maybe `$EXT` (defined as `EXT=so`) was meant instead? the meaning of some of the variable names isn't very obvious to the random reader...

**Comment by bilam** [comment]
the exact file name of libgmp depends on distro. It is libgmp.so.10 on debian and redhat derivatives.
What is the output on arch liinux if executing the following sentences?

/sbin/ldconfig -p | grep libgmp

**Comment by herrvonvoid** [comment]
```
$> /sbin/ldconfig -p | grep libgmp
        libgmpxx.so.4 (libc6,x86-64) => /usr/lib/libgmpxx.so.4
        libgmpxx.so (libc6,x86-64) => /usr/lib/libgmpxx.so
        libgmp.so.10 (libc6,x86-64) => /usr/lib/libgmp.so.10
        libgmp.so (libc6,x86-64) => /usr/lib/libgmp.so
```

**Comment by bilam** [comment]
You are correct. I mixed up libgmp with libjgmp. The extension should be GEXT=so
Fix will be available in the next release. Thank you for reporting and the fix.
