### ISSUE TITLE
regression: ijconsole.sh fails

### ISSUE THREAD

**Issue by herrvonvoid** [jsoftware/jsource#177]
latest archlinux; j9.4 installed with `bin/install-usr.sh` from linux64 download with applied fixes for #175 (add `|| true` to the update-alternatives line) and #176 (`GEXT=so`)

`/usr/bin/ijconsole.sh` fails with `/usr/bin/ijconsole.sh: line 2: /usr/bin/ijconsole: No such file or directory`

it is obvious why this is: the fix for #175 results in not creating the file needed and skipping the else branch which is `(cd $BIN && ln -sf ijconsole-9.4 ijconsole)`

if we use `||(cd $BIN && ln -sf ijconsole-9.4 ijconsole)` instead of `||true` it works.

note: `(cd foo && bar)` puts you back where you are so if you use an if clause instead you need to manually do that. (that was news to me)

nitpick: since we are handling the case that update-alternatives isn't available, it would be nice imo to suppress the error message by redirecting it to /dev/null

**Comment by bilam** [comment]
I have already put (cd $BIN && ln -sf ijconsole-9.5 ijconsole) in my last patch.
