### ISSUE TITLE
[Feature Request] Private assignment =. to scope only to containing line if used outside of explicit definition {{…}}

### ISSUE THREAD

**Issue by cchando** [jsoftware/jsource#200]
The proposed change would solve the longstanding issue of local assignment not being available for tacit definitions, which causes tacit code to unavoidably pollute the global namespace when defining helper verbs. In particular, this would make local scoping for tacit verbs practical in conjunction with the addition of the proposed <code>…</code> for line continuation. 

This is in the same spirit as the different scoping of <code>$:</code> inside vs. outside of an explicit definition.

Currently <code>=.</code> has the same meaning as <code>=:</code> outside of explicit definitions.

**Comment by cdburke** [comment]
Usually scripts are loaded by an explicit definition, so local definitions are local to that definition, and not global.

**Comment by cchando** [comment]
Hmm, ok. I'm surprised to hear that this would necessitate too many changes to documentation besides the NuVoc page... and I would think that we could safely assume that user scripts wouldn't rely on using <code>=.</code> to mean the same thing as <code>=:</code>. But, oh well. 

If anyone can help clarify for me the specific scope of things that would hypothetically need to be changed by this (as an example), it would greatly help me in understanding the ramifications of future feature requests, so I can avoid making unrealistic requests.

Separately, the motivation here was to be able to define helper verb <code>f</code> locally to a given tacit verb, and still have <code>f</code> available to mean something else globally. And/or have it available to mean something else locally within the definition of another tacit verb. All of this is within a single script.
