### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by 89z** [jsoftware/jsource#27]
If I download this:

https://github.com/jsoftware/jsource/releases/download/build/w64.zip

Extract, and run `j64\jconsole.exe`, I get this:

~~~
Load library C:\j64\j.dll failed: The specified module could not be found.
~~~

which is confusing, as `C:\j64\j.dll` does exist on my computer.

**Comment by cdburke** [comment]
Thanks. libomp.dll has been added to the build, which should fix the problem.
