### ISSUE TITLE
x and y in adverbs and conjunctions

### ISSUE THREAD

**Issue by tangentstorm** [jsoftware/jsource#32]
```
   + 1 :'y' 0
|value error: y
|       y
   + 1 :'v=.y' 0
0
```
Could we at some point have an option to turn off the situational definition of x and y -- where x really means u and y really means v if neither u nor v are present? 

-- @rdm <2007-11-05T22:06:46Z)>

**Comment by HenryHRich** [comment]
Done in J9.02
