### ISSUE TITLE
>:^:_3

### ISSUE THREAD

**Issue by lalucas** [jsoftware/jsource#45]
If   >:^:3 adds 3,  shouldn't  >:^:_3  subtract 3?

It works fine for a single number but not for a list of numbers. For example:

(>:^:_3) 5 3 _2 _1

gives 2 which is 5-3

**Comment by interregna** [comment]
Seems to work here. Perhaps include a version and the complete results if your results differ.

```
   (>:^:_3) 5 3 _2 _1
2 0 _5 _4

   JVERSION
Engine: j903/j64avx/darwin
Beta-o: commercial/2021-08-24T19:02:18
Library: 9.03.06
Qt IDE: 1.9.3/5.15.2(5.15.2)
Platform: Darwin 64
Installer: J903 install
InstallPath: /applications/j903-current
Contact: www.jsoftware.com
```

**Comment by lalucas** [comment]
It doesn't work here.

My version is
j902/j64avx2/windows

[image: image.png]



Em ter., 14 de set. de 2021 às 16:13, interregna ***@***.***>
escreveu:

**Comment by eiverson** [comment]
Just tried your expression in 902 and 903. It looks like a bug in 902. It
works as expected in 903 beta. Thanks for the report and we'll take a more
detailed look.

**Comment by rdm** [comment]
It looks like this has been fixed in j903. Please re-open with details (including especially something about the kind of machine you're using) if this is still a problem.
