### ISSUE TITLE
Semiduals

### ISSUE THREAD

**Issue by tangentstorm** [jsoftware/jsource#46]
*(from j wiki)*

Enhance `&.` and `&.:`

``u&.:(n`v)`` is equivalent to ``x v^:_1@(u v) v``

``u&.:(v`n)`` is equivalent to ``x v^:_1@(u~ v)~ v``

and

``u&.(n`v)`` is equivalent to ``x u&.:(n`v)"(n,mv) v``

``u&.(v`n)`` is equivalent to ``x u&.:(v`n)"(mv,n) v``

Dual, but applying v only to one argument.

Example: ``x^y`` is ``x *&.(^.`0) y``

As part of this change, u`v will be extended so that if u and v have different types, boxopen will be applied to each.

-- Henry Rich

**Comment by tangentstorm** [comment]
@HenryHRich is this already done? I see we have semiduals. I can't tell if that was implemented because of this request, or whether this is a request to use numeric `n` for the rank, instead of just allowing `a:` for `n` as we have now.

**Comment by HenryHRich** [comment]
Done mostly, no more needed
