### ISSUE TITLE
Data teleport

### ISSUE THREAD

**Issue by tangentstorm** [jsoftware/jsource#59]
A simple way to overcome trains dataflow restrictions would be a primitive to establish a data pipe ("teleport") between arbitrary code points. It is described on page Data teleport.

-- [Igor Zhuravlov](https://code.jsoftware.com/wiki/User:Igor_Zhuravlov 02:47, 3 September 2019 (UTC)

**Comment by tangentstorm** [comment]
I think pronouns (aka 'variables') satisfy this description? --  @rdm 14:59, 4 September 2019 (UTC)

**Comment by jip** [comment]
Just for reference: [Data teleport](https://code.jsoftware.com/wiki/User:Igor_Zhuravlov/Data_teleport) page.

**Comment by rdm** [comment]
Igor left a comment on my talk page -- https://code.jsoftware.com/wiki/User_talk:Raul_Miller -- "_Now I see this simple idea can be easily implemented by plain J, so there is no need to touch the interpreter._"

So I am closing this issue.
