### ISSUE TITLE
Don't print input prompt in jconsole when stdin is not interactive

### ISSUE THREAD

**Issue by rsaarelm** [jsoftware/jsource#7]
I want to be able to do this:

    $ echo '2 2 $ 1' | jconsole
    1 1
    1 1

However, when I try this, the output looks like this:

    $ echo "2 2 $ 1" | jconsole
       1 1
    1 1

Jconsole is printing the three spaces of input prompt even though it's being run in a noninteractive session. On linux, you should be able to see that the session is noninteractive when `isatty(stdin)` is false. Would it be possible to suppress printing the input prompt to stdout when this is the case?

Related stackoverflow question about the same thing: https://stackoverflow.com/questions/20348167/how-to-get-a-nice-output-when-calling-jconsole

**Comment by eiverson** [comment]
Interesting question and a reasonable request. Years ago there was a
facility for changing the prompt that would have solved your problem, but
it was dropped.

I note that the prompt indent also effect the next linux term prompt.

You might play with the following as a workaround:

echo {.a.[echo i.2 3 4[echo {.a.|jconsole

You could define cecho to wrap this up.

Questions like this will get a much wider audience and better answers if
you subscribed to the J programming forum. Or perhaps to the stackoverflow
J tag if you prefer.

**Comment by rsaarelm** [comment]
I'm making a literate programming style "interactive notebook" tool that takes inline sequences of J statements and splices the output back into the file (pretty much same as the people in the linked stackoverflow question). The current workaround hack is to insert line `echo ''` before the last line of each block if the last line is not `)` and filter blank lines from the output, but I'd rather not have the script need to have any understanding of J semantics and the `)` special case is already hacky. This also requires that only the last line of each block processed prints anything, although so far this seems to work reasonably well with my use pattern of short snippets that either just define things silently or print a single value at the end.

The isatty approach would solve this at the jconsole end, since based on the old stackoverflow answer this seems actually reasonably hard to deal with robustly on the user side, and wouldn't require new options to be added.

**Comment by bilam** [comment]
The prompt indent is an inheritance/artefact from APL. An cleaner approach
is to add an 9!:xx to enable/disable the prompt.

Incidentally the prompt is troublesome to get it right when J sentences are
executed asynchronously.

**Comment by rsaarelm** [comment]
A command that can be added to the start of a script that disables the prompt would solve the problem for me. My program can add lines to the script it generates without needing to be able to parse J.

**Comment by bilam** [comment]
fixed now
